[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "food farm bonus evoke upset tunnel local balcony spin brush mimic pilot major base organ fire clump sudden credit lucky goddess topple curve talk"
